### ISSUE TITLE
[Bug / FR] Avoid duplicates in the file list

### ISSUE THREAD

**Issue by stef-rausch** [rodrez/obsidian-harpoon#1]
`Harpoon` is a very useful plugin -- thank you for it!

Currently, one can add up to four harpoons to the same file.

It would be great if the plugin would only allow one mark for the same note in the file list.

Cheers

**Comment by rodrez** [comment]
That makes a lot of sense I'll take a look at this tonight.

**Comment by rodrez** [comment]
Fix implemented.

**Comment by stef-rausch** [comment]
Thank you!
