### ISSUE TITLE
Ability to Edit and Remove Files from Harpoon List

### ISSUE THREAD

**Issue by santiyounger** [rodrez/obsidian-harpoon#10]
Hey thanks for this awesome plugin, is there a current method to easily edit the list of files in my harpoon list, otherwise this would be a great feature to add, because I added some files to my list I no longer need

Thanks

**Comment by rodrez** [comment]
You should be able to press the key "d" twice, and that should work. Let me know if that's not working.

On the home page of the plugin, there's a section for shortcuts that might be helpful.

Thanks for reaching out, I'm glad the plugging is helpful.

**Comment by santiyounger** [comment]
very cool shortcut (vim style) thank you, it'd definitely be nice to have an `X` remove button to make it more beginner friendly, but only if you get the chance, thanks
