### ISSUE TITLE
Newline Charater added to beginning of file if already focused

### ISSUE THREAD

**Issue by ScumbagScalawag** [rodrez/obsidian-harpoon#3]
A New line character is added to be beginning of the file when you are on that same file and press enter. 

## Steps to reproduce
1. Open harpoon menu
2. Press enter on the file that was just in focus 

A new line is added to the beginning of the file (even before the new "properties"). 

Note also I tried this with and without vim mode active and with default theme (I was desperate lol) and It still persists. 

Running Obsidian on Fedora Linux if that matters. Can try to reproduce on windows machine if you can't reproduce this bug.

**Comment by rodrez** [comment]
Thanks! I'll try to replicate it today, I'll get back to you if I have any questions.

**Comment by rodrez** [comment]
@ScumbagScalawag Fix implemented. Please let me know if you continue to face issues.
