### ISSUE TITLE
FR: Set cursor to the beginning of the file switched to / Remember and switch to last cursor position in a harpooned file.

### ISSUE THREAD

**Issue by stef-rausch** [rodrez/obsidian-harpoon#5]
Would it be possible to implement the, in the title, requested separate (optional) features?

Currently, when switching harpooned files, the cursor "lands" at the end of the document. For others, this might be okay, but for me, it is annoying.

I installed the plugin and like it so far!

**Comment by rodrez** [comment]
Hi there,

I'll try to give this a look tonight.

**Comment by rodrez** [comment]
Just small update. I worked on this a bit, cursor is now remembered but need to add scroll to position. Caveat cursor is only remembered when using shortcuts, will add more functionality to also remember when clicking other files, although possibly only if the files are 'hooked' by the plugin. @StefanoRausch 

Won't release an update until I get the scroll stuff fix. Maybe tomorrow...

**Comment by stef-rausch** [comment]
Thank you so much; you did it!
